server:
  ssl:
    enabled: true
    key-alias: tomcat
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: bookstore
spring:
  application:
    name: gateway
  cloud:
    gateway:
      # Java routes API does not support default filters
      # https://github.com/spring-cloud/spring-cloud-gateway/issues/263
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary, RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS
      routes:
        - uri: "lb://SEARCH-SERVICE"
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1
        - uri: "lb://MAIN-SERVICE"
          predicates:
            - Path=/**
      httpclient:
        ssl:
          use-insecure-trust-manager: true
eureka:
  instance:
    secure-port-enabled: true
    hostname: bookstore.gpx.moe
    non-secure-port-enabled: false
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka